spring:
  datasource:
    username: root
    password: GJ670068
    url: jdbc:mysql://localhost:3306/cainiaoshop_wms
    type: com.mysql.cj.jdbc.MysqlDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: cainiaoshop-ware
  jackson:
    date-format: java.text.SimpleDateFormat
mybatis-plus:

  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 11000